### ISSUE TITLE
Make web front-end usable

### ISSUE THREAD

**Issue by baylee** [angelicahill/shakespearescanner#2]
I imagine this has two main components

1. Accepting user input through a form
2. Showing another web view with the response from your server

For the server parts, I recommend you look at this resource: https://gowebexamples.com/ up through the Forms section (can skip MySQL database section for now).

For the HTML parts, I suggest you read up on HTML forms if you haven't had a lot of experience: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Your_first_HTML_form

**Comment by angelicahill** [comment]
Thank you will look at https://gowebexamples.com/ 👍 and the HTML resource and then work on getting it all running in my app.
